### PR TITLE
EDD Calculation with LMP && GE on CareCard Done

### PR DESCRIPTION
**Pull request by enumahin**

### CODE REVIEW

**Comment by enumahin** [comment]
Note: I created a file adult-initial-evaluation.html and copied all the code in a file with the same name from Tega's branch into the one I created and then modified my version.

**Comment by wandechris** [comment]
@enumahin this request has conflicts, what you should do is work off Tega's branch not copy the files

**Comment by enumahin** [comment]
Please what do you mean by working off Tega's branch?

**Comment by wandechris** [comment]
@enumahin create a new branch from Tega's branch before you make your changes

**Pull request closed without merging**
