### PR TITLE
First PCR/ Age at Test

### PR DESCRIPTION
**Pull request by Ebuka-John**
Issues resolved, First PCR/ Age at Test,
Mothers Registration Information/ Descriptive Address, and 
Feeding Decision/ Mixed was resolved

in child follow-up form and delivery register

### CODE REVIEW

**Comment by tobstech** [comment]
Hi @vigosofts, why did you delete the new fields for sample collections in the child follow-up form under PCR? Those fields are added to help aid EMR-LIMS exchange for EID Samples. Kindly revert it. This pull request cannot be merged at the moment.

**Comment by Adeyemicodes** [comment]
Hello @tobstech, I made a pull request likewise which had the correct update but it seems missing or deleted. Can you confirm?

**Comment by tobstech** [comment]
are you referring to the **new** branch?

**Comment by Adeyemicodes** [comment]
Yes

**Comment by tobstech** [comment]
Alright. That was fine. and it has been merged. Welldone.

**Comment by Adeyemicodes** [comment]
Thanks bro

**Pull request closed without merging**
